# Regression test for #869:
# Generation of PB_STATIC_ASSERT can lead to an identified that exceeds compiler maximum length

Import("env")

env.SkipTestIfFlag('PB_NO_RECURSION')

env.NanopbProto("bigfile.proto")
env.Object("bigfile.pb.c")
