# Regression test for #558:
# Manually defining proto3:true on a field with default value incorrectly omits it when encoding.

Import("env")
env.NanopbProto("mixed")

test = env.Program(["mixed.c", "mixed.pb.c", env['NANOPB_OBJS']])
env.RunTest(test)
