# Build and run a basic test for floating point default values.

Import("env")

env.NanopbProto("floats")
test = env.Program(["infinity_nan_test.c", "floats.pb.c", env['NANOPB_DECODER_OBJS']])

env.RunTest(test)
