local_repository(
    name = "nanopb",
    path = "../..",
)

load("@nanopb//extra/bazel:nanopb_deps.bzl", "nanopb_deps")

nanopb_deps()

load("@nanopb//extra/bazel:python_deps.bzl", "nanopb_python_deps")

nanopb_python_deps()

load("@nanopb//extra/bazel:nanopb_workspace.bzl", "nanopb_workspace")

nanopb_workspace()
