# Regression test for #647:
# Ill-formed oneof message leads to calling free on an arbitrary pointer

Import("env")
env.SkipTestIfFlag('PB_NO_MALLOC')

env.NanopbProto("repro.proto")

test = env.Program(["repro.c", "repro.pb.c", env['NANOPB_OBJS']])
env.RunTest(test)
