#!/usr/bin/env python3
# This file is used to invoke nanopb_validate_generator.py as a plugin
# to protoc on Linux and other *nix-style systems.
# Use it like this:
# protoc --plugin=protoc-gen-nanopb-validate=..../protoc-gen-nanopb-validate \
#        --nanopb_out=--protoc-insertion-points:dir \
#        --nanopb-validate_out=dir foo.proto
#
# Note that --nanopb_out must come first: this plugin injects into the files
# that nanopb generates, and protoc runs generators in command line order.

from nanopb_validate_generator import *

if __name__ == '__main__':
    # Assume we are running as a plugin under protoc.
    main_plugin()
