#!/usr/bin/env python3
# This file acts as a drop-in replacement of binary protoc.exe.
# It will use either Python-based protoc from grpcio-tools package,
# or if it is not available, protoc.exe from path if found.

import sys
import os
import os.path
import tempfile

# Depending on how this script is run, we may or may not have PEP366 package name
# available for relative imports.
if not __package__:
    from proto._utils import has_grpcio_protoc, invoke_protoc
else:
    from .proto._utils import has_grpcio_protoc, invoke_protoc

if __name__ == '__main__':
    # Get path of the directory where this script is stored.
    if getattr(sys, 'frozen', False):
        mypath = os.path.dirname(sys.executable) # For pyInstaller

        # The whole point of the binary package is to include grpcio,
        # so better to report it as error if it the import fails.
        assert has_grpcio_protoc(verbose = True)
    else:
        mypath = os.path.dirname(__file__)

    # Avoid recursive calls to self
    env_paths = os.environ["PATH"].split(os.pathsep)
    if mypath in env_paths:
        env_paths.remove(mypath)
        os.environ["PATH"] = os.pathsep.join(env_paths)

    # Add arguments for finding the generator plugins when using --nanopb_out=
    # or --nanopb-validate_out= arguments to protoc.
    def _make_python_wrapper(target_path, name):
        """Create an executable launcher for non-executable plugin scripts."""
        wrapper_path = os.path.join(tempfile.gettempdir(), name + "-launcher")
        wrapper_code = (
            "#!/usr/bin/env python3\n"
            "import os\n"
            "import sys\n"
            "os.execv(sys.executable, [sys.executable, %r] + sys.argv[1:])\n"
        ) % target_path

        with open(wrapper_path, 'w') as wrapper:
            wrapper.write(wrapper_code)

        os.chmod(wrapper_path, 0o755)
        return wrapper_path

    def find_plugin(name):
        if os.path.isfile(os.path.join(mypath, name + ".exe")):
            return os.path.join(mypath, name + ".exe")
        elif os.name == 'nt':
            return os.path.join(mypath, name + ".bat")
        else:
            plugin_path = os.path.join(mypath, name)
            if os.path.isfile(plugin_path) and not os.access(plugin_path, os.X_OK):
                return _make_python_wrapper(plugin_path, name)
            return plugin_path

    args = sys.argv[1:]

    for plugin in ("protoc-gen-nanopb", "protoc-gen-nanopb-validate"):
        path = find_plugin(plugin)
        if os.path.isfile(path):
            args = ['--plugin=%s=%s' % (plugin, path)] + args

    status = invoke_protoc(['protoc'] + args)
    sys.exit(status)
