Import('env')
decode_unittests = env.Object("decode_unittests.c", CPPPATH = ['$NANOPB/src', env['CPPPATH']])
p = env.Program([decode_unittests, "$COMMON/unittestproto.pb.c", "$COMMON/malloc_wrappers.c"])
env.RunTest(p)

