Import('env')
env = env.Clone()
env.Append(CPPPATH = ['$NANOPB/src']) # To get nanopb source files internals
p = env.Program(["decode_unittests.c", "$COMMON/unittestproto.pb.c", "$COMMON/malloc_wrappers.c"])
env.RunTest(p)

