# Check that callback fields inside malloc()ed messages
# are correctly initialized.

Import('env')
env.SkipTestIfFlag('PB_NO_MALLOC')
env.SkipTestIfFlag('PB_NO_DEFAULT_ALLOCATOR')

env.NanopbProto('callback_pointer')

p = env.Program(["callback_pointer.c",
                 "callback_pointer.pb.c",
                 env['NANOPB_OBJS']])

# Run test under valgrind if available
kwargs = {}
if env.get("VALGRIND"):
    kwargs['COMMAND'] = env['VALGRIND']
    kwargs['ARGS'] = ["-q", "--error-exitcode=99", p[0].abspath]

env.RunTest(p, **kwargs)

