# Test functions in pb_common.c

Import('env')
common_unittests = env.Object("common_unittests.c", CPPPATH = ['$NANOPB/src', env['CPPPATH']])
p = env.Program([common_unittests, "$BUILD/alltypes/alltypes.pb.c"])
env.RunTest(p)
