# Run the alltypes test case, but compile with PB_BUFFER_ONLY=1

Import("env")

# Take copy of the files for custom build.
c = Copy("$TARGET", "$SOURCE")
env.Command("alltypes.pb.h", "$BUILD/alltypes/alltypes.pb.h", c)
env.Command("alltypes.pb.c", "$BUILD/alltypes/alltypes.pb.c", c)
env.Command("encode_alltypes.c", "$BUILD/alltypes/encode_alltypes.c", c)
env.Command("decode_alltypes.c", "$BUILD/alltypes/decode_alltypes.c", c)
env.Command("big_message.pb.h", "$BUILD/big_message/big_message.pb.h", c)
env.Command("big_message.pb.c", "$BUILD/big_message/big_message.pb.c", c)
env.Command("decode_big_message.c", "$BUILD/big_message/decode_big_message.c", c)
env.Command("encode_big_message.c", "$BUILD/big_message/encode_big_message.c", c)

# Define the compilation options
opts = env.Clone()
opts.Append(CPPDEFINES = {'PB_BUFFER_ONLY': 1})

# Build new version of core
strict = opts.Clone()
strict.Append(CFLAGS = strict['CORECFLAGS'])
strict.Object("pb_decode_bufonly.o", "$NANOPB/pb_decode.c")
strict.Object("pb_encode_bufonly.o", "$NANOPB/pb_encode.c")
strict.Object("pb_common_bufonly.o", "$NANOPB/pb_common.c")

# Now build and run the test normally.
enc = opts.Program(["encode_alltypes.c", "alltypes.pb.c", "pb_encode_bufonly.o", "pb_common_bufonly.o"])
dec = opts.Program(["decode_alltypes.c", "alltypes.pb.c", "pb_decode_bufonly.o", "pb_common_bufonly.o"])

big_enc = opts.Program(["encode_big_message.c", "big_message.pb.c", "pb_encode_bufonly.o", "pb_common_bufonly.o"])
big_dec = opts.Program(["decode_big_message.c", "big_message.pb.c", "pb_decode_bufonly.o", "pb_common_bufonly.o"])

env.RunTest(enc)
env.RunTest([dec, "encode_alltypes.output"])

env.RunTest(big_enc)
env.RunTest([big_dec, "encode_big_message.output"])
