# Test the functionality of the callback fields.

Import("env")

env.NanopbProto("callbacks")
enc = env.Program(["encode_callbacks.c", "callbacks.pb.c", env['NANOPB_ENCODER_OBJS']])
dec = env.Program(["decode_callbacks.c", "callbacks.pb.c", env['NANOPB_DECODER_OBJS']])

env.RunTest(enc)
env.RunTest([dec, "encode_callbacks.output"])

env.Decode(["encode_callbacks.output", "callbacks.proto"], MESSAGE = "TestMessage")
env.Compare(["decode_callbacks.output", "encode_callbacks.decoded"])

