# Test stack usage
# This test case intentionally performs access outside the legal stack area,
# so it may have to be skipped to avoid false positives on memory safety tools.

Import("env")

if not env.get("NOUNSAFE"):
    env.NanopbProto(["stackusage", "stackusage.options"])
    test = env.Program(["stackusage.c", "stackusage.pb.c", env['NANOPB_OBJS']])
    env.RunTest(test)
