Import("env")

env.SkipTestIfFlag('PB_NO_MALLOC')

env.NanopbProto("mem_release.proto")

test = env.Program(["mem_release.c",
                    "mem_release.pb.c",
                    env['NANOPB_OBJS']])

env.RunTest(test)

