env = DefaultEnvironment()

# Add the builders defined in site_init.py
add_nanopb_builders(env)

# Path to the files shared by tests, and to the nanopb core.
env.Append(CPPPATH = ["#../", "#common"])

# Path for finding nanopb.proto
env.Append(PROTOCPATH = ['#../generator', '/usr/include', '.'])

# Define the include path to find nanopb.proto
env.Append(PROTOCPATH = ['#../generator', '/usr/include', '.'])

# Now include the SConscript files from all subdirectories
SConscript(Glob('*/SConscript'), exports = 'env')

