# Test wrapping of a C++ class inside struct using callback_datatype option.
Import('env')

if env.get('EMBEDDED') == 'AVR':
    Return() # No <vector> on AVR g++

import os

opts = env.Clone()
opts.Replace(NANOPBFLAGS = '--cpp-descriptor')
opts.NanopbProtoCpp('message')

# not enabled for "c++03", which fails with "warning: offset of on non-POD type 'TestMessage'"
# 'offsetof' in C++98 requires POD type, C++11 standard relaxes that to standard-layout class.
# see: http://www.cplusplus.com/reference/cstddef/offsetof/

test = opts.Program(['cxx_callback_datatype.cpp', 'message.pb.cpp', env['NANOPB_OBJS']])
opts.RunTest(test)
