# Check that pb_release() correctly handles corrupted size fields of
# static arrays.

Import('malloc_env')
env = malloc_env

env.NanopbProto('size_corruption')

p = env.Program(["size_corruption.c",
                 "size_corruption.pb.c",
                 "$COMMON/pb_decode_with_malloc.o",
                 "$COMMON/pb_common_with_malloc.o",
                 "$COMMON/malloc_wrappers.o"])
env.RunTest(p)

