# Check that pb_release() correctly handles corrupted size fields of
# static arrays.

Import('env')


env.NanopbProto('size_corruption')

p = env.Program(["size_corruption.c",
                 "size_corruption.pb.c",
                 env['NANOPB_OBJS']])
env.RunTest(p)

