# Test cxx descriptor functionality

Import('env')

opts = env.Clone()
opts.Replace(NANOPBFLAGS = '--cpp-descriptor')
opts.NanopbProto('message')

test = opts.Program(['message_descriptor.cc', 'message.pb.c', env['NANOPB_OBJS']])
opts.RunTest(test)
