# Build and run a test that encodes and decodes a message that contains
# all of the Protocol Buffers data types.

Import("env")

env.NanopbProto("alltypes")
enc = env.Program(["encode_alltypes.c", "alltypes.pb.c", "#common/pb_encode.o"])
dec = env.Program(["decode_alltypes.c", "alltypes.pb.c", "#common/pb_decode.o"])

env.RunTest(enc)
env.RunTest([dec, "encode_alltypes.output"])

