# Regression test for #504:
# Non empty submessage considered empty on FT_POINTER fields with address aligned on 0x100

Import('env', 'env')

env.NanopbProto(["test.proto"])
test = env.Program(["test.c",
                 "test.pb.c",
                 env['NANOPB_ENCODER_OBJS']
                 ])

env.RunTest(test)
