/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8-dev at Fri Feb 10 11:25:26 2017. */

#include "api.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t HelloRequest_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, POINTER , FIRST, HelloRequest, test_string, test_string, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, HelloRequest, dummy_number, test_string, 0),
    PB_LAST_FIELD
};

const pb_field_t HelloResponse_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, CALLBACK, FIRST, HelloResponse, test_string, test_string, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, HelloResponse, dummy_number, test_string, 0),
    PB_LAST_FIELD
};

const pb_field_t UartConfig_fields[5] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, UartConfig, speed, speed, 0),
    PB_FIELD(  2, UENUM   , REQUIRED, STATIC  , OTHER, UartConfig, data_size, speed, 0),
    PB_FIELD(  3, UENUM   , REQUIRED, STATIC  , OTHER, UartConfig, parity, data_size, 0),
    PB_FIELD(  4, UENUM   , REQUIRED, STATIC  , OTHER, UartConfig, stop_bits, parity, 0),
    PB_LAST_FIELD
};

const pb_field_t SendRequest_fields[3] = {
    PB_FIELD(  1, MESSAGE , OPTIONAL, STATIC  , FIRST, SendRequest, uart_config, uart_config, &UartConfig_fields),
    PB_FIELD(  2, BYTES   , REQUIRED, CALLBACK, OTHER, SendRequest, data, uart_config, 0),
    PB_LAST_FIELD
};





/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(SendRequest, uart_config) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_HelloRequest_HelloResponse_UartConfig_SendRequest)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(SendRequest, uart_config) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_HelloRequest_HelloResponse_UartConfig_SendRequest)
#endif


/* @@protoc_insertion_point(eof) */
