# Verify that the maximum encoded size is calculated properly
# for enums.

Import('env')

env.NanopbProto('enums')

p = env.Program(["enum_encoded_size.c",
                 "enums.pb.c",
                 env['NANOPB_ENCODER_OBJS']
                 ])
env.RunTest(p)

