# Simulate io errors when encoding and decoding

Import("env")

c = Copy("$TARGET", "$SOURCE")
env.Command("alltypes.proto", "#alltypes/alltypes.proto", c)

env.NanopbProto(["alltypes", "alltypes.options"])

ioerr = env.Program(["io_errors.c", "alltypes.pb.c",
                     env['NANOPB_OBJS']])

env.RunTest("io_errors.output", [ioerr, "$BUILD/alltypes/encode_alltypes.output"])


