# Build and run a basic round-trip test using direct stream encoding.

Import("env")

env.SkipTestIfFlag('PB_NO_STREAM_CALLBACK')

enc = env.Program(["encode_stream.c", "$COMMON/person.pb.c", env['NANOPB_ENCODER_OBJS']])
dec = env.Program(["decode_stream.c", "$COMMON/person.pb.c", env['NANOPB_DECODER_OBJS']])

env.RunTest(enc)
env.RunTest([dec, "encode_stream.output"])
env.Decode(["encode_stream.output", "$COMMON/person.proto"], MESSAGE = "Person")
env.Compare(["decode_stream.output", "encode_stream.decoded"])

