# Regression test for #1017:
# Test that missing required fields are correctly reported by all streams.

Import("env")

env.NanopbProto("test.proto")

p = env.Program(["test.c",
                 "test.pb.c",
                 "$COMMON/pb_decode.o",
                 "$COMMON/pb_common.o"])

env.RunTest(p)
