# Build and run the stand-alone unit tests for the nanopb encoder part.

Import('env')
encode_unittests = env.Object("encode_unittests.c", CPPPATH = ['$NANOPB/src', env['CPPPATH']])
p = env.Program([encode_unittests, "$COMMON/unittestproto.pb.c", "$COMMON/malloc_wrappers.c"])
env.RunTest(p)
