# Build and run the stand-alone unit tests for the nanopb encoder part.

Import('env')
p = env.Program(["encode_unittests.c", "$COMMON/unittestproto.pb.c", "$COMMON/malloc_wrappers.c"])
env.RunTest(p)
