# Test namingstyle option

Import('env')

env = env.Clone()
env.Replace(NANOPBFLAGS = "-C,--cpp-descriptor")

env.NanopbProto(["naming_style", "naming_style.options"])

test = env.Program(["test_naming_style_c.c", "naming_style.pb.c", "$COMMON/pb_decode.o", "$COMMON/pb_encode.o", '$COMMON/pb_common.o'])
env.RunTest(test)

test2 = env.Program(["test_cxx_descriptor.cc", "naming_style.pb.c", "$COMMON/pb_decode.o", "$COMMON/pb_encode.o", '$COMMON/pb_common.o'])
env.RunTest(test2)
