# Test that fixed count option works.

Import("malloc_env")

malloc_env.NanopbProto("fixed_count")
malloc_env.Object("fixed_count.pb.c")

p = malloc_env.Program(["fixed_count_unittests.c",
                 "fixed_count.pb.c",
                 "$COMMON/pb_encode_with_malloc.o",
                 "$COMMON/pb_decode_with_malloc.o",
                 "$COMMON/pb_common_with_malloc.o",
                 "$COMMON/malloc_wrappers.o"])

malloc_env.RunTest(p)
