# Test that fixed count option works.

Import("env")

env.NanopbProto("fixed_count")
env.Object("fixed_count.pb.c")

p = env.Program(["fixed_count_unittests.c",
                 "fixed_count.pb.c",
                 env['NANOPB_OBJS']])

env.RunTest(p)
