# Regression test for #1061
# submsg_callback with FT_CALLBACK

Import("env")
env.SkipTestIfFlag('PB_NO_STRUCT_FIELD_CALLBACK')

env.NanopbProto("submsg_ft_callback")
env.Object("submsg_ft_callback.pb.c")

p = env.Program(["test.c",
                 "submsg_ft_callback.pb.c",
                 env['NANOPB_OBJS']
                 ])

env.RunTest(p)
