# Test namingstyle option

Import('env')

env = env.Clone()
env.Replace(NANOPBFLAGS = "--custom-style=custom_naming_style.CustomNamingStyle")

style = Command("custom_naming_style.py", "../../namingstyle_custom/custom_naming_style.py", Copy("$TARGET", "$SOURCE"))

proto = env.NanopbProto(["custom_naming_style", "custom_naming_style.options"])
Depends(proto, style)
proto = env.NanopbProto(["custom_naming_style_package", "custom_naming_style_package.options"])
Depends(proto, style)
proto = env.NanopbProto(["custom_naming_style_mangle", "custom_naming_style_mangle.options"])
Depends(proto, style)

proto = env.NanopbProto(["custom_naming_style_other", "custom_naming_style_other.options"])
Depends(proto, style)
proto = env.NanopbProto(["custom_naming_style_importer", "custom_naming_style_importer.options", "custom_naming_style_other", "custom_naming_style_other.options"])
Depends(proto, style)

test = env.Program(["test_custom_naming_style_c.c", "custom_naming_style.pb.c", env['NANOPB_OBJS']])
mangle = env.Program(["test_custom_naming_style_mangle_c.c", "custom_naming_style_mangle.pb.c", env['NANOPB_OBJS']])
package = env.Program(["test_custom_naming_style_package_c.c", "custom_naming_style_package.pb.c", env['NANOPB_OBJS']])
importer = env.Program(["test_custom_naming_style_importer_c.c", "custom_naming_style_importer.pb.c", "custom_naming_style_other.pb.c", env['NANOPB_OBJS']])

env.RunTest(test)
env.RunTest(mangle)
env.RunTest(package)
env.RunTest(importer)
