# Regression test for security issue GHSA-gcx3-7m76-287p
# "Out-of-memory condition on repeated field can result in invalid free()"

Import("env")

env.NanopbProto("test")

test = env.Program(["test.c", "test.pb.c", env['NANOPB_OBJS']])
                          
env.RunTest([test, 'test_input.pb'])
