# Regression test for #631:
# Wrong initializer generation

Import("env")

env.NanopbProto("submsg_callback.proto")
t = env.Program(["test.c", "submsg_callback.pb.c", env['NANOPB_OBJS']])
env.RunTest(t)
