# Regression test for #376:
# Problem with fixed array inside proto3 submessage

Import("env")

env.NanopbProto(["fixed_array.proto", "fixed_array.options"])
testprog = env.Program(["test_fixarray.c",
                 "fixed_array.pb.c",
                 env['NANOPB_OBJS']
                 ])

env.RunTest(testprog)

