# Regression test for Issue 253: Wrong calculated message maximum size

Import('env')

env.NanopbProto('short_array')

p = env.Program(['short_array.c',
                 'short_array.pb.c', 
                 env['NANOPB_OBJS']
                 ])

env.RunTest(p)


