# Build the common files needed by multiple test cases

from SCons.Environment import apply_tools

Import('env')

# apply_tools(env, tools = ['nanogrpc'])

# Protocol definitions for the encode/decode_unittests
# TODO change this ugly way of compiling protofiles from place that is
# outside working tree. I didn't manage to do ti even i classic makefile
# withoud cd to directory with that file.
copy = env.Command('dummy.file', [], 'cd ../nanogrpc && protoc --plugin=../generator/protoc-gen-nanopb --nanopb_out=../tests/build/nanogrpc nanogrpc.proto')
env.AlwaysBuild(copy)
