# Test the support for extension fields.

Import("env")

# We use the files from the alltypes test case
incpath = env.Clone()
incpath.Append(PROTOCPATH = '$BUILD/alltypes')
incpath.Append(CPPPATH = '$BUILD/alltypes')

incpath.NanopbProto(["extensions", "extensions.options"])
enc = incpath.Program(["encode_extensions.c", "extensions.pb.c", "$BUILD/alltypes/alltypes.pb$OBJSUFFIX", env['NANOPB_ENCODER_OBJS']])
dec = incpath.Program(["decode_extensions.c", "extensions.pb.c", "$BUILD/alltypes/alltypes.pb$OBJSUFFIX", env['NANOPB_DECODER_OBJS']])

env.RunTest(enc)
env.RunTest([dec, "encode_extensions.output"])

