# Test the support for extension fields.

Import("env")

# We use the files from the alltypes test case
incpath = env.Clone()
incpath.Append(PROTOCPATH = '#alltypes')
incpath.Append(CPPPATH = '#alltypes')

incpath.NanopbProto("extensions")
enc = incpath.Program(["encode_extensions.c", "extensions.pb.c", "#alltypes/alltypes.pb$OBJSUFFIX", "#common/pb_encode.o"])
dec = incpath.Program(["decode_extensions.c", "extensions.pb.c", "#alltypes/alltypes.pb$OBJSUFFIX", "#common/pb_decode.o"])

env.RunTest(enc)
env.RunTest([dec, "encode_extensions.output"])

