# Regression test for #395:
# Unexpected empty submessage in proto3 mode

Import("env")

env.NanopbProto(["test.proto", "test.options"])
testprog = env.Program(["test.c",
                 "test.pb.c",
                 env['NANOPB_OBJS']
                 ])

env.RunTest(testprog)

