# Regression test for issue #547:
# Buffer overflow when encoding bytes with size set to 65535

Import("env")

env.NanopbProto("test.proto")

# Build and run test
test = env.Program(["test.c", "test.pb.c", env['NANOPB_ENCODER_OBJS']])

env.RunTest(test)
