# Regression test for #363:
# Incorrect PB_STATIC_ASSERT for bytes inside oneof

Import("env")

env.NanopbProto("oneofmsg.proto")
testprog = env.Program(["test_oneofmsg.c",
                 "oneofmsg.pb.c",
                 env['NANOPB_OBJS']
                 ])

env.RunTest(testprog)

