# Regression test for Issue 249: proto3 mode pb_decode() corrupts callback fields
Import('env')

env.NanopbProto('test')

p = env.Program(["test.c",
                 "test.pb.c",
                 env['NANOPB_OBJS']
                 ])
env.RunTest(p)

