# Regression test for security issue GHSA-p24j-vqcp-x988
# "Callback inside oneof can result in call to attacker-controlled function pointer"

Import("env")

env.NanopbProto("submsg_ft_callback.proto")
env.NanopbProto("variant.proto")

poc_master = env.Program(["poc_master.c", "submsg_ft_callback.pb.c", env['NANOPB_DECODER_OBJS']])
env.RunTest([poc_master])

poc_release = env.Program(["poc_release.c", "variant.pb.c", env['NANOPB_DECODER_OBJS']])
env.RunTest([poc_release])

if not env.HasFlag('PB_NO_STRUCT_FIELD_CALLBACK'):
    poc_positive = env.Program(["poc_positive.c", "variant.pb.c", env['NANOPB_DECODER_OBJS']])
    env.RunTest([poc_positive])
