/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "alltypes_legacy.h"
#if PB_PROTO_HEADER_VERSION != 93
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SubMessage, SubMessage, S)


PB_BIND(EmptyMessage, EmptyMessage, S)


PB_BIND(Limits, Limits, S)


PB_BIND(AllTypes, AllTypes, S)







#if !PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

