# Check that the old generated .pb.c/.pb.h files are still compatible with the
# current version of nanopb.

Import("env")

enc = env.Program(["encode_legacy.c", "alltypes_legacy.c", env['NANOPB_ENCODER_OBJS']])
dec = env.Program(["decode_legacy.c", "alltypes_legacy.c", env['NANOPB_DECODER_OBJS']])

env.RunTest(enc)
env.RunTest([dec, "encode_legacy.output"])

