# Test that special characters in .proto filenames work.

Import('env')

env.Proto("funny-proto+name has.characters.proto")
env.Nanopb("funny-proto+name has.characters.pb.c", "funny-proto+name has.characters.pb")
env.Object("funny-proto+name has.characters.pb.c")
