# Regression test for #342:
# Possible null-pointer dereference in pb_decode.c

Import("env")

env.NanopbProto("extensions")
testprog = env.Program(["test_extensions.c", "extensions.pb.c", env['NANOPB_OBJS']])

env.RunTest(testprog)

