# Regression test for #544:
# Decoding whole submessage in submessage callback causes "missing required field"

Import("env")
env.NanopbProto("submsg_callback")

test = env.Program(["submsg_callback.c", "submsg_callback.pb.c", env['NANOPB_OBJS']])
env.RunTest(test)
