/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8-dev at Tue Feb 21 23:25:18 2017. */

#ifndef NG_FILEPROTO_NG_H_INCLUDED
#define NG_FILEPROTO_NG_H_INCLUDED
#include <pb.h>
#include <ng.h>
#include <nanogrpc.h>

#include "fileproto.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Services definitions */
extern ng_service_t FileServer_service;
extern ng_method_t FileServer_ListFiles_method;
ng_GrpcStatus_t FileServer_service_init();

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
