/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8-dev at Tue Feb 21 23:25:18 2017. */

#include "fileproto.ng.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



DEFINE_FILL_WITH_ZEROS_FUNCTION(Path)
DEFINE_FILL_WITH_ZEROS_FUNCTION(FileList)

ng_service_t FileServer_service = {
    "FileServer",
    0,
    NULL,
};

ng_method_t FileServer_ListFiles_method = {
    "ListFiles",
    0,
    NULL,
    NULL,
    NULL,
    Path_fields,
    &FILL_WITH_ZEROS_FUNCTION_NAME(Path),
    NULL,
    FileList_fields,
    &FILL_WITH_ZEROS_FUNCTION_NAME(FileList),
    NULL,
};


ng_GrpcStatus_t FileServer_service_init(){
    ng_addMethodToService(&FileServer_service, &FileServer_ListFiles_method);
    return 0;
}

/* @@protoc_insertion_point(eof) */
