# Check that default values with special characters are
# correctly handled.

Import('env')

env.NanopbProto('defaults')

p = env.Program(["defaults.c",
                 "defaults.pb.c",
                 env['NANOPB_DECODER_OBJS']
                 ])

env.RunTest(p)

