# Regression test for Issue 229: problem encoding message that has
# multiple oneof fields
Import('env')

env.NanopbProto('multiple_oneof')

p = env.Program(["multiple_oneof.c",
                 "multiple_oneof.pb.c",
                 env['NANOPB_OBJS']
                 ])
env.RunTest(p)

