# Test that the int_size option in .proto works.

Import('env')

env.NanopbProto('intsizes')

p = env.Program(["intsizes_unittests.c",
                 "intsizes.pb.c",
                 env['NANOPB_OBJS']
                 ])
env.RunTest(p)
