# Test that inlined bytes fields work.

Import("env")

env.NanopbProto("inline")
env.Object("inline.pb.c")

env.Match(["inline.pb.h", "inline.expected"])

p = env.Program(["inline_unittests.c",
                 "inline.pb.c",
                 env['NANOPB_OBJS']
                 ])

env.RunTest(p)
