# Example / test for handling 'map' type using the backwards compatibility
# in protobuf specification:
# https://developers.google.com/protocol-buffers/docs/proto3#maps

Import('env')

env.NanopbProto(['map', 'map.options'])

enc = env.Program(['encode_map.c',
                'map.pb.c',
                env['NANOPB_ENCODER_OBJS'],
                ])

dec = env.Program(['decode_map.c',
                'map.pb.c',
                env['NANOPB_DECODER_OBJS'],
                ])

env.RunTest("message.pb", enc)
env.RunTest("message.txt", [dec, 'message.pb'])

