# This builds a simple utility that decodes a binary protobuf message.
# It is similar to protoc --decode_raw, except it produces useful information
# even for corrupted messages.

Import("env")

env.SkipTestIfFlag('PB_NO_STREAM_CALLBACK')

dec = env.Program(["raw_decode.c", env['NANOPB_DECODER_OBJS']])

env.RunTest([dec, "$BUILD/alltypes/encode_alltypes.output"])

