# Test that pb_check_proto3_default_value() correctly skips padding
# bytes in submessage structures.

Import("env")

env.NanopbProto("padding")

p = env.Program(["padding.c",
                 "padding.pb.c",
                 env['NANOPB_ENCODER_OBJS']
                 ])

env.RunTest(p)

