# Test sort_by_tag generator option

Import("env")

env.NanopbProto(["sort_by_tag.proto", "sort_by_tag.options"])
test = env.Program(["sort_by_tag.c", "sort_by_tag.pb.c", env['NANOPB_OBJS']])
env.RunTest(test)

